//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace System.Globalization
{
	public enum Culture
	{
		Default=127,
		/// <summary>
		/// Afrikaans
		/// </summary>
		AF = 54,
		/// <summary>
		/// Amharic
		/// </summary>
		AM = 94,
		/// <summary>
		/// Arabic
		/// </summary>
		AR = 1,
		/// <summary>
		/// Assamese
		/// </summary>
		AS = 77,
		/// <summary>
		/// Azeri
		/// </summary>
		AZ = 44,
		/// <summary>
		/// Bashkir
		/// </summary>
		BA = 109,
		/// <summary>
		/// Belarusian
		/// </summary>
		BE = 35,
		/// <summary>
		/// Bulgarian
		/// </summary>
		BG = 2,
		/// <summary>
		/// Bengali
		/// </summary>
		BN = 69,
		/// <summary>
		/// Tibetan
		/// </summary>
		BO = 81,
		/// <summary>
		/// Breton
		/// </summary>
		BR = 126,
		/// <summary>
		/// Bosnian
		/// </summary>
		BS = 30746,
		/// <summary>
		/// Catalan
		/// </summary>
		CA = 3,
		/// <summary>
		/// Corsican
		/// </summary>
		CO = 131,
		/// <summary>
		/// Czech
		/// </summary>
		CS = 5,
		/// <summary>
		/// Welsh
		/// </summary>
		CY = 82,
		/// <summary>
		/// Danish
		/// </summary>
		DA = 6,
		/// <summary>
		/// German
		/// </summary>
		DE = 7,
		/// <summary>
		/// Divehi
		/// </summary>
		DV = 101,
		/// <summary>
		/// Greek
		/// </summary>
		EL = 8,
		/// <summary>
		/// English
		/// </summary>
		EN = 9,
		/// <summary>
		/// Spanish
		/// </summary>
		ES = 10,
		/// <summary>
		/// Estonian
		/// </summary>
		ET = 37,
		/// <summary>
		/// Basque
		/// </summary>
		EU = 45,
		/// <summary>
		/// Persian
		/// </summary>
		FA = 41,
		/// <summary>
		/// Fulah
		/// </summary>
		FF = 103,
		/// <summary>
		/// Finnish
		/// </summary>
		FI = 11,
		/// <summary>
		/// Faroese
		/// </summary>
		FO = 56,
		/// <summary>
		/// French
		/// </summary>
		FR = 12,
		/// <summary>
		/// Frisian
		/// </summary>
		FY = 98,
		/// <summary>
		/// Irish
		/// </summary>
		GA = 60,
		/// <summary>
		/// Scottish Gaelic
		/// </summary>
		GD = 145,
		/// <summary>
		/// Galician
		/// </summary>
		GL = 86,
		/// <summary>
		/// Guarani
		/// </summary>
		GN = 116,
		/// <summary>
		/// Gujarati
		/// </summary>
		GU = 71,
		/// <summary>
		/// Hausa
		/// </summary>
		HA = 104,
		/// <summary>
		/// Hebrew
		/// </summary>
		HE = 13,
		/// <summary>
		/// Hindi
		/// </summary>
		HI = 57,
		/// <summary>
		/// Croatian
		/// </summary>
		HR = 26,
		/// <summary>
		/// Hungarian
		/// </summary>
		HU = 14,
		/// <summary>
		/// Armenian
		/// </summary>
		HY = 43,
		/// <summary>
		/// Indonesian
		/// </summary>
		ID = 33,
		/// <summary>
		/// Igbo
		/// </summary>
		IG = 112,
		/// <summary>
		/// Yi
		/// </summary>
		II = 120,
		/// <summary>
		/// Icelandic
		/// </summary>
		IS = 15,
		/// <summary>
		/// Italian
		/// </summary>
		IT = 16,
		/// <summary>
		/// Inuktitut
		/// </summary>
		IU = 93,
		/// <summary>
		/// Japanese
		/// </summary>
		JA = 17,
		/// <summary>
		/// Basa Jawa
		/// </summary>
		JV = 4096,
		/// <summary>
		/// Georgian
		/// </summary>
		KA = 55,
		/// <summary>
		/// Kazakh
		/// </summary>
		KK = 63,
		/// <summary>
		/// Greenlandic
		/// </summary>
		KL = 111,
		/// <summary>
		/// Khmer
		/// </summary>
		KM = 83,
		/// <summary>
		/// Kannada
		/// </summary>
		KN = 75,
		/// <summary>
		/// Korean
		/// </summary>
		KO = 18,
		/// <summary>
		/// Central Kurdish
		/// </summary>
		KU = 146,
		/// <summary>
		/// Kyrgyz
		/// </summary>
		KY = 64,
		/// <summary>
		/// Luxembourgish
		/// </summary>
		LB = 110,
		/// <summary>
		/// Lao
		/// </summary>
		LO = 84,
		/// <summary>
		/// Lithuanian
		/// </summary>
		LT = 39,
		/// <summary>
		/// Latvian
		/// </summary>
		LV = 38,
		/// <summary>
		/// Malagasy
		/// </summary>
		MG = 4096,
		/// <summary>
		/// Maori
		/// </summary>
		MI = 129,
		/// <summary>
		/// Macedonian (FYROM)
		/// </summary>
		MK = 47,
		/// <summary>
		/// Malayalam
		/// </summary>
		ML = 76,
		/// <summary>
		/// Mongolian
		/// </summary>
		MN = 80,
		/// <summary>
		/// Marathi
		/// </summary>
		MR = 78,
		/// <summary>
		/// Malay
		/// </summary>
		MS = 62,
		/// <summary>
		/// Maltese
		/// </summary>
		MT = 58,
		/// <summary>
		/// Burmese
		/// </summary>
		MY = 85,
		/// <summary>
		/// Norwegian (Bokmål)
		/// </summary>
		NB = 31764,
		/// <summary>
		/// Nepali
		/// </summary>
		NE = 97,
		/// <summary>
		/// Dutch
		/// </summary>
		NL = 19,
		/// <summary>
		/// Norwegian (Nynorsk)
		/// </summary>
		NN = 30740,
		/// <summary>
		/// Norwegian
		/// </summary>
		NO = 20,
		/// <summary>
		/// Occitan
		/// </summary>
		OC = 130,
		/// <summary>
		/// Oromo
		/// </summary>
		OM = 114,
		/// <summary>
		/// Oriya
		/// </summary>
		OR = 72,
		/// <summary>
		/// Punjabi
		/// </summary>
		PA = 70,
		/// <summary>
		/// Polish
		/// </summary>
		PL = 21,
		/// <summary>
		/// Pashto
		/// </summary>
		PS = 99,
		/// <summary>
		/// Portuguese
		/// </summary>
		PT = 22,
		/// <summary>
		/// Romansh
		/// </summary>
		RM = 23,
		/// <summary>
		/// Romanian
		/// </summary>
		RO = 24,
		/// <summary>
		/// Russian
		/// </summary>
		RU = 25,
		/// <summary>
		/// Kinyarwanda
		/// </summary>
		RW = 135,
		/// <summary>
		/// Sanskrit
		/// </summary>
		SA = 79,
		/// <summary>
		/// Sindhi
		/// </summary>
		SD = 89,
		/// <summary>
		/// Sami (Northern)
		/// </summary>
		SE = 59,
		/// <summary>
		/// Sinhala
		/// </summary>
		SI = 91,
		/// <summary>
		/// Slovak
		/// </summary>
		SK = 27,
		/// <summary>
		/// Slovenian
		/// </summary>
		SL = 36,
		/// <summary>
		/// chiShona
		/// </summary>
		SN = 4096,
		/// <summary>
		/// Somali
		/// </summary>
		SO = 119,
		/// <summary>
		/// Albanian
		/// </summary>
		SQ = 28,
		/// <summary>
		/// Serbian
		/// </summary>
		SR = 31770,
		/// <summary>
		/// Southern Sotho
		/// </summary>
		ST = 48,
		/// <summary>
		/// Swedish
		/// </summary>
		SV = 29,
		/// <summary>
		/// Kiswahili
		/// </summary>
		SW = 65,
		/// <summary>
		/// Tamil
		/// </summary>
		TA = 73,
		/// <summary>
		/// Telugu
		/// </summary>
		TE = 74,
		/// <summary>
		/// Tajik
		/// </summary>
		TG = 40,
		/// <summary>
		/// Thai
		/// </summary>
		TH = 30,
		/// <summary>
		/// Tigrinya
		/// </summary>
		TI = 115,
		/// <summary>
		/// Turkmen
		/// </summary>
		TK = 66,
		/// <summary>
		/// Setswana
		/// </summary>
		TN = 50,
		/// <summary>
		/// Turkish
		/// </summary>
		TR = 31,
		/// <summary>
		/// Tsonga
		/// </summary>
		TS = 49,
		/// <summary>
		/// Tatar
		/// </summary>
		TT = 68,
		/// <summary>
		/// Uyghur
		/// </summary>
		UG = 128,
		/// <summary>
		/// Ukrainian
		/// </summary>
		UK = 34,
		/// <summary>
		/// Urdu
		/// </summary>
		UR = 32,
		/// <summary>
		/// Uzbek
		/// </summary>
		UZ = 67,
		/// <summary>
		/// Vietnamese
		/// </summary>
		VI = 42,
		/// <summary>
		/// Wolof
		/// </summary>
		WO = 136,
		/// <summary>
		/// isiXhosa
		/// </summary>
		XH = 52,
		/// <summary>
		/// Yoruba
		/// </summary>
		YO = 106,
		/// <summary>
		/// Chinese
		/// </summary>
		ZH = 30724,
		/// <summary>
		/// isiZulu
		/// </summary>
		ZU = 53
	}
}